# Generated by Django 4.1 on 2023-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_players20_defending_alter_players20_dribbling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players20',
            name='release_clause_eur',
            field=models.BooleanField(blank=True, null=True, verbose_name='Release Clause (EUR)'),
        ),
    ]
