# Generated by Django 4.1 on 2023-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_players20_release_clause_eur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players20',
            options={'ordering': ['overall']},
        ),
        migrations.AlterField(
            model_name='players20',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='attacking_crossing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attacking Crossing'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='attacking_finishing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attacking Finishing'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='attacking_heading_accuracy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attacking Heading Accuracy'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='attacking_short_passing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attacking Short Passing'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='attacking_volleys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attacking Volleys'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='body_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Body Type'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='cam',
            field=models.IntegerField(blank=True, null=True, verbose_name='CAM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='cb',
            field=models.IntegerField(blank=True, null=True, verbose_name='CB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='cdm',
            field=models.IntegerField(blank=True, null=True, verbose_name='CDM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='cf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CF'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='club',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='CM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='contract_valid_until',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contract Valid Until'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='defending_marking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defending Marking'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='defending_sliding_tackle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defending Sliding Tackle'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='defending_standing_tackle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defending Standing Tackle'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='goalkeeping_diving',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goalkeeping Diving'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='goalkeeping_handling',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goalkeeping Handling'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='goalkeeping_kicking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goalkeeping Kicking'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='goalkeeping_positioning',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goalkeeping Positioning'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='goalkeeping_reflexes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goalkeeping Reflexes'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='international_reputation',
            field=models.IntegerField(blank=True, null=True, verbose_name='International Reputation'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Joined'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lam',
            field=models.IntegerField(blank=True, null=True, verbose_name='LAM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lb',
            field=models.IntegerField(blank=True, null=True, verbose_name='LB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lcb',
            field=models.IntegerField(blank=True, null=True, verbose_name='LCB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lcm',
            field=models.IntegerField(blank=True, null=True, verbose_name='LCM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='ldm',
            field=models.IntegerField(blank=True, null=True, verbose_name='LDM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lf',
            field=models.IntegerField(blank=True, null=True, verbose_name='LF'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lm',
            field=models.IntegerField(blank=True, null=True, verbose_name='LM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='loaned_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loaned From'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Long Name'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='ls',
            field=models.IntegerField(blank=True, null=True, verbose_name='LS'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lw',
            field=models.IntegerField(blank=True, null=True, verbose_name='LW'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='lwb',
            field=models.IntegerField(blank=True, null=True, verbose_name='LWB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_aggression',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Aggression'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_composure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Composure'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_interceptions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Interceptions'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Penalties'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_positioning',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Positioning'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='mentality_vision',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mentality Vision'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='movement_acceleration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movement Acceleration'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='movement_agility',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movement Agility'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='movement_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movement Balance'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='movement_reactions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movement Reactions'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='movement_sprint_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movement Sprint Speed'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='nation_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nation Position'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='overall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Overall'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='player_positions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player Positions'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='player_tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player Tags'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='player_traits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player Traits'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='player_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player URL'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='potential',
            field=models.IntegerField(blank=True, null=True, verbose_name='Potential'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='power_jumping',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Jumping'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='power_long_shots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Long Shots'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='power_shot_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Shot Power'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='power_stamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Stamina'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='power_strength',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Strength'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferred Foot'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rb',
            field=models.IntegerField(blank=True, null=True, verbose_name='RB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rcb',
            field=models.IntegerField(blank=True, null=True, verbose_name='RCB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rcm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RCM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rdm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RDM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='real_face',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Real Face'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='release_clause_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Release Clause (EUR)'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rf',
            field=models.IntegerField(blank=True, null=True, verbose_name='RF'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RM'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rs',
            field=models.IntegerField(blank=True, null=True, verbose_name='RS'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rw',
            field=models.IntegerField(blank=True, null=True, verbose_name='RW'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='rwb',
            field=models.IntegerField(blank=True, null=True, verbose_name='RWB'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_ball_control',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill Ball Control'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_curve',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill Curve'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_dribbling',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill Dribbling'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_fk_accuracy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill FK Accuracy'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_long_passing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill Long Passing'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='skill_moves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skill Moves'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='sofifa_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Sofifa ID'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='st',
            field=models.IntegerField(blank=True, null=True, verbose_name='ST'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='team_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team Position'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='value_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value (EUR)'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='wage_eur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wage (EUR)'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='weak_foot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weak Foot'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='players20',
            name='work_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Work Rate'),
        ),
    ]
